name: tappy_toes
description: Tappy Toes - Baby kick tracker app
publish_to: 'none'
version: 1.0.4+4

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
